<a href="https://colab.research.google.com/github/Triwka/ml_homework/blob/main/ML_HW_FORALL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="https://github.com/Triwka/ml_homework/blob/main/gifs/start.gif?raw=1" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [ ]:
str1 = "ada"
str2 = "lovelace"
str3 = "was considered the world's first computer programmer.               "
res = str1.capitalize() + str2.capitalize() + str3
res

"AdaLovelacewas considered the world's first computer programmer.               "

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [ ]:
res = res.strip()
res

"AdaLovelacewas considered the world's first computer programmer."

3. Найти первое вхождение в строку подстроки (☆☆☆)

In [ ]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"
s = s1.split('#')
s
##your code

['Holy',
 'cow,',
 'Rick!',
 'I',
 'didn’t',
 'know',
 'hanging',
 'out',
 'with',
 'you',
 'was',
 'making',
 'me',
 'smarter!']

5. Полученный массив строк склеить через пробел (★☆☆)

In [ ]:
res = ''
for i in s:
  res = res + i + ' '
res


'Holy cow, Rick! I didn’t know hanging out with you was making me smarter! '

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}
for key in personal_data:
  print (personal_data[key][0], '(age',personal_data[key][1],')', 'is a', personal_data[key][2])


Ann (age 29 ) is a Artist
Leo (age 54 ) is a Programmer
Tiffany (age 43 ) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [ ]:
a = int (input())
if a % 4 == 0 and a % 100 > 0 or a % 400 == 0 :
    print('YES')
else :
    print('NO')

283
NO


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [ ]:
words = ['Not', 'my', 'cup', 'of', 'tea']
mydict = {}
for i in range(len(words)):
  mydict[words[i]]=i
mydict

{'Not': 0, 'my': 1, 'cup': 2, 'of': 3, 'tea': 4}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
del dogs[1]
dogs

['border collie', 'labrador retriever']

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
del dogs[dogs.index('australian cattle dog')]
dogs

['border collie', 'labrador retriever']

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [ ]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']
new_li = [x.upper() for x in dogs[2:5]]
new_li

['AUSTRALIAN', 'CATTLE', 'DOG']

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }
for key in pets:
  mydict = pets[key]
  st = "Name is {dogname}, kind is {kind}, owner is {owner}, vaccine status : {vac_stat}".format(dogname = key, kind = mydict['kind'], owner = mydict['owner'] , vac_stat = mydict['vaccinated'])
  print(st)


Name is willie, kind is dog, owner is eric, vaccine status : True
Name is walter, kind is cockroach, owner is eric, vaccine status : False
Name is peso, kind is dog, owner is chloe, vaccine status : True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [ ]:
a=set([2, 5, 6 ])
b=set([2, 4, 8, 3, 5, 6])
a < b
##your code

True

13. Объединить несколько множеств (★☆☆)

In [ ]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])
myset = a.union(b.union(c))
myset
##your code

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [ ]:
b.intersection(c)

{4, 5, 35}

In [ ]:
b.intersection(a)

{5, 6, 35}

In [ ]:
b.intersection(myset)

{2, 3, 4, 5, 6, 8, 35}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [ ]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])
a.symmetric_difference(b)
##your code

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame()

In [ ]:
my_dict = {}
with open ('mlhw.txt') as txt:
    my_dict = {}
    for line in txt:
        line = tuple(line.strip().split(','))
        my_dict[line[0]] = line[1:]
df = pd.DataFrame(my_dict, index = ['age','debt','occupation'])
df


Adrianov Varlamov   Streletskiy   Volnov Shkredov
age              25       31            33       45       22
debt          30000    45000        120000    45000    30000
occupation   artist  builder  psychologist  builder   artist

In [ ]:
df = df.T
df

age    debt    occupation
Adrianov     25   30000        artist
Varlamov     31   45000       builder
Streletskiy  33  120000  psychologist
Volnov       45   45000       builder
Shkredov     22   30000        artist

In [ ]:
df.occupation.nunique()

3

In [ ]:
my_dict

{'Adrianov': ('25', '30000', 'artist'),
 'Varlamov': ('31', '45000', 'builder'),
 'Streletskiy': ('33', '120000', 'psychologist'),
 'Volnov': ('45', '45000', 'builder'),
 'Shkredov': ('22', '30000', 'artist')}

Непонятно как сохранить количество уникальных профессий в json

### os, sys, datetime

In [ ]:
import os

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [ ]:
import os

path = os.getcwd()
with os.scandir(path) as listOfEntries:
    for entry in listOfEntries:
        if entry.is_file():
            print(entry.name)

Rotating_earth_(large).gif
cars_moldova_cat_num.xls
giphy.gif


In [ ]:
import os 
 
try: 
  files = os.listdir('gifs') 
  print(files) 
  gifs = [] 
  for file in files: 
    if file.endswith('.gif'): 
      gifs.append(file) 
  print(gifs) 
except: 
  pass

['Rotating_earth_(large).gif', 'cars_moldova_cat_num.xls', 'giphy.gif', '4cbe8d_f1ed2800a49649848102c68fc5a66e53mv2.webp']
['Rotating_earth_(large).gif', 'giphy.gif']


сложно

18. Создать папку с названием temp и удалить её (★☆☆)

In [ ]:
os.mkdir("temp")
os.rmdir("temp")

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [ ]:
os.environ

environ{'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1',
        'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2',
        'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2',
        'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
        'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2',
        'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19',
        'CLOUDSDK_PYTHON': 'python3',
        'LANG': 'en_US.UTF-8',
        'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1',
        'HOSTNAME': 'e082056703b6',
        'OLDPWD': '/',
        'CLOUDSDK_CONFIG': '/content/.config',
        'NV_LIBNPP_VERSION': '11.3.2.152-1',
        'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1',
        'NVIDIA_VISIBLE_DEVICES': 'all',
        'NV_NVPROF_VERSION': '11.2.152-1',
        'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1',
        'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"de

20. Как игнорировать warrnings?

In [ ]:
import warnings 
warnings.simplefilter("ignore", UserWarning)

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [ ]:
dir(datetime.date)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'ctime',
 'day',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'min',
 'month',
 'replace',
 'resolution',
 'strftime',
 'timetuple',
 'today',
 'toordinal',
 'weekday',
 'year']

In [ ]:
import datetime

In [ ]:
today = datetime.date.today()
today

datetime.date(2022, 10, 23)

In [ ]:
today + datetime.timedelta(days=1)

datetime.date(2022, 10, 24)

In [ ]:
today - datetime.timedelta(days=1)

datetime.date(2022, 10, 22)

22. Вывести день недели сегодняшней даты (★☆☆)

In [ ]:
datetime.date.weekday(today)

6

23. Получить список дат за предыдущую неделю (★★☆)

In [ ]:
today = datetime.datetime.today()
print(today)

2022-10-23 16:50:30.252021


In [ ]:
for i in range (7):
  print(today  - datetime.timedelta(days=i))

2022-10-23 16:50:30.252021
2022-10-22 16:50:30.252021
2022-10-21 16:50:30.252021
2022-10-20 16:50:30.252021
2022-10-19 16:50:30.252021
2022-10-18 16:50:30.252021
2022-10-17 16:50:30.252021


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [ ]:
td = datetime.datetime.now().strftime('%d.%m.%Y %X')
td

'23.10.2022 16:42:48'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [ ]:
datetime.datetime.today()

datetime.datetime(2022, 10, 23, 16, 47, 24, 730539)

In [ ]:
datetime.datetime.today() - datetime.timedelta(days = datetime.date.weekday(today))

datetime.datetime(2022, 10, 17, 16, 47, 48, 642062)

# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [ ]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [ ]:
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [ ]:
data.size

10

In [ ]:
data.itemsize

8

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [ ]:
data = np.zeros(10)
data[4]=1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [ ]:
data = np.arange(10,51)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [ ]:
data[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [ ]:
test = np.array([[1,2],[3,4]])
test

array([[1, 2],
       [3, 4]])

In [ ]:
test[0][0]

1

In [ ]:
data = np.arange(0,9)
data = data.reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
data[0][0]

0

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [ ]:
data = np.array([1,2,0,0,4,0])
data

array([1, 2, 0, 0, 4, 0])

In [ ]:
data.nonzero()

(array([0, 1, 4]),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [ ]:
data = np.random.random((10,10))
data, data.min(), data.max(), data.mean()

(array([[0.6353548 , 0.6866722 , 0.66918491, 0.98946635, 0.44091143,
         0.59717441, 0.75423519, 0.76302807, 0.49794211, 0.9827222 ],
        [0.02638952, 0.56420734, 0.91637625, 0.05320724, 0.53039514,
         0.93638673, 0.52417641, 0.74847379, 0.74928178, 0.39832089],
        [0.99778873, 0.1168949 , 0.84066059, 0.64496565, 0.47135446,
         0.50879298, 0.78504153, 0.69565102, 0.85107666, 0.77986633],
        [0.28362421, 0.15607546, 0.53478008, 0.91370195, 0.14663259,
         0.12549146, 0.32026429, 0.96907331, 0.42469073, 0.73179067],
        [0.21418415, 0.34879419, 0.257821  , 0.45022625, 0.91583281,
         0.93977137, 0.21210411, 0.38043568, 0.81180032, 0.07029444],
        [0.91844011, 0.76821068, 0.67156123, 0.07554422, 0.56165833,
         0.26149396, 0.25161632, 0.10067961, 0.35465298, 0.56874677],
        [0.70407965, 0.26562246, 0.59000606, 0.95828425, 0.19826912,
         0.52330362, 0.15735622, 0.89554953, 0.55019118, 0.47579702],
        [0.71652194, 0.4871

In [ ]:
data = np.random.randint((10,10))
data

array([9, 7])

In [ ]:
data = np.random.random_integers((10,10))
data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, (10, 10) + 1) instead
  """Entry point for launching an IPython kernel.


TypeError: ignored

Как создать матрицу из рандомных но целочисленных значений?

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [ ]:
data = np.zeros((8,8))
data[1::2,::2] = 1
data[::2,1::2] = 1
data

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [ ]:
data = np.random.random((10,10))
res = (data - data.mean())/data.std()
data, res

(array([[0.49988062, 0.03168964, 0.94744486, 0.09845917, 0.89405762,
         0.07084962, 0.3056866 , 0.14787541, 0.55352738, 0.55644611],
        [0.60932766, 0.64324925, 0.43053352, 0.77845523, 0.44333827,
         0.57415957, 0.0246298 , 0.49745786, 0.27136312, 0.30111701],
        [0.45473922, 0.17542317, 0.49064684, 0.94675606, 0.21695358,
         0.486351  , 0.90722572, 0.48901297, 0.10173757, 0.77363005],
        [0.63996877, 0.55267532, 0.70124829, 0.41887886, 0.43246119,
         0.95312956, 0.53750183, 0.76532002, 0.95949259, 0.64887171],
        [0.67831516, 0.09272203, 0.379243  , 0.37176438, 0.98194695,
         0.52346733, 0.98676936, 0.7691575 , 0.41354554, 0.86054881],
        [0.95932148, 0.5887852 , 0.94634034, 0.94386696, 0.09357898,
         0.40691162, 0.94110252, 0.68080241, 0.66352368, 0.65735106],
        [0.71006195, 0.18638346, 0.69057019, 0.41562677, 0.24421429,
         0.25715588, 0.0972656 , 0.36287675, 0.89768894, 0.89278263],
        [0.63583681, 0.3210

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [ ]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆) * (6 способов)

In [ ]:
data = np.random.uniform(0,5,5)
data

array([3.88605805, 4.48644634, 3.1067402 , 2.08259443, 4.72419417])

In [ ]:
print(data - data%1) # 1
print(data // 1) # 2
print(np.floor(data)) # 3
print(data.astype(int)) # 4
print(np.trunc(data)) # 5

[3. 4. 3. 2. 4.]
[3. 4. 3. 2. 4.]
[3. 4. 3. 2. 4.]
[3 4 3 2 4]
[3. 4. 3. 2. 4.]


In [ ]:
int_arr = []
for i in data:
  int_arr.append(int(i))
int_arr # 6

[3, 4, 3, 2, 4]

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [ ]:
data = np.random.random(10)
data

array([0.99676778, 0.08653236, 0.05142831, 0.65751645, 0.70222971,
       0.77152941, 0.63513928, 0.44966355, 0.94641263, 0.4271525 ])

In [ ]:
data.sort()
data

array([0.05142831, 0.08653236, 0.4271525 , 0.44966355, 0.63513928,
       0.65751645, 0.70222971, 0.77152941, 0.94641263, 0.99676778])

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [ ]:
arr_1 = np.random.random(10)
arr_2 = np.random.random(10)
arr_1, arr_2

(array([0.4326169 , 0.70504386, 0.89557847, 0.02306627, 0.89352155,
        0.2031755 , 0.91214954, 0.2277993 , 0.20769345, 0.34371672]),
 array([0.41954078, 0.05168596, 0.8113448 , 0.94302783, 0.79002805,
        0.82466245, 0.19379181, 0.98164472, 0.11541053, 0.50051193]))

In [ ]:
np.allclose(arr_1,arr_2)

False

In [ ]:
np.array_equal(arr_1,arr_2)

False

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [ ]:
data = np.random.random(10)
data[data.argmax()] = 0
data

array([0.86408815, 0.68186423, 0.33316809, 0.43166277, 0.        ,
       0.87636269, 0.89429429, 0.35074615, 0.69720443, 0.35196615])

16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index  = (np.abs(Z-v)).argmin() 
print(Z[index])

80


In [ ]:
v

80.21880192938286

17. Посчитать среднее для каждой строки матрицы (★★☆)

In [ ]:
data = np.array([[1,2],[3,4],[5,6]])
data, data.mean(axis=1)

(array([[1, 2],
        [3, 4],
        [5, 6]]), array([1.5, 3.5, 5.5]))

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [ ]:
res = np.cumsum(data)
res = (res[3:] - res [:-3]) / 3
res

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18.])

<img src="https://github.com/Triwka/ml_homework/blob/main/gifs/bender.gif?raw=1" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [ ]:
import re

In [ ]:
result = re.findall(r'................................_', "master_guid':'233880bb4c50d247f84edc9cac9e6e29_2308194320")
result
s = str(result[0])
s
res = s[:-1]
res

'233880bb4c50d247f84edc9cac9e6e29'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849